Food_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food_app/', include('food_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_app/urls.py
from django.urls import path

from .views import IndexView, UserRegisterView, UserActiveView, UserLoginView, UserLogoutView, UserPanelView, \
    UserUpdateView, UserPasswordUpdateView, UserPasswordResetView, UserPasswordSetView, UserDeleteView, \
        UserRecipeView, UserScheduleView, UserIngredientView, UserCommentView, UserLikeView, UserLikeScheduleView, \
            UserRecipesView, UserSchedulesView, UserCommentsView, IngredientCreateView, IngredientUpdateView, \
                IngredientDeleteView, RecipeCreateView, RecipeUpdateView, RecipeDeleteView, RecipeDetailView, \
                    RecipeListView, ScheduleCreateView, ScheduleUpdateView, ScheduleDeleteView, ScheduleDetailView, \
                        ScheduleListView

urlpatterns = [
    path('', view=IndexView.as_view(), name='index'),
    path('user/register/', view=UserRegisterView.as_view(), name='user-register'),
    path('user/active/', view=UserActiveView.as_view(), name='user-active'),
    path('user/login/', view=UserLoginView.as_view(), name='user-login'),
    path('user/logout/', view=UserLogoutView.as_view(), name='user-logout'),
    path('user/panel/', view=UserPanelView.as_view(), name='user-panel'),
    path('user/update/', view=UserUpdateView.as_view(), name='user-update'),
    path('user/password/update/', view=UserPasswordUpdateView.as_view(), name='user-password-update'),
    path('user/password/reset/', view=UserPasswordResetView.as_view(), name='user-password-reset'),
    path('user/password/set/', view=UserPasswordSetView.as_view(), name='user-password-set'),
    path('user/delete/', view=UserDeleteView.as_view(), name='user-delete'),
    path('user/recipe/', view=UserRecipeView.as_view(), name='user-recipe'),
    path('user/schedule/', view=UserScheduleView.as_view(), name='user-schedule'),
    path('user/ingredient/', view=UserIngredientView.as_view(), name='user-ingredient'),
    path('user/comment/', view=UserCommentView.as_view(), name='user-comment'),
    path('user/like/', view=UserLikeView.as_view(), name='user-like'),
    path('user/like_schedule/', view=UserLikeScheduleView.as_view(), name='user-like-schedule'),
    path('user/recipes/<int:pk>/', view=UserRecipesView.as_view(), name='user-recipes'),
    path('user/schedules/<int:pk>/', view=UserSchedulesView.as_view(), name='user-schedules'),
    path('user/comments/<int:pk>/', view=UserCommentsView.as_view(), name='user-comments'),
    path('ingredient/create/', view=IngredientCreateView.as_view(), name='ingredient-create'),
    path('ingredient/update/<int:pk>/', view=IngredientUpdateView.as_view(), name='ingredient-update'),
    path('ingredient/delete/<int:pk>/', view=IngredientDeleteView.as_view(), name='ingredient-delete'),
    path('recipe/create/', view=RecipeCreateView.as_view(), name='recipe-create'),
    path('recipe/update/<int:pk>/', view=RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipe/delete/<int:pk>/', view=RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipe/detail/<int:pk>/', view=RecipeDetailView.as_view(), name='recipe-detail'),
    path('recipe/list/', view=RecipeListView.as_view(), name='recipe-list'),
    path('schedule/create/', view=ScheduleCreateView.as_view(), name='schedule-create'),
    path('schedule/update/<int:pk>/', view=ScheduleUpdateView.as_view(), name='schedule-update'),
    path('schedule/delete/<int:pk>/', view=ScheduleDeleteView.as_view(), name='schedule-delete'),
    path('schedule/detail/<int:pk>/', view=ScheduleDetailView.as_view(), name='schedule-detail'),
    path('schedule/list/', view=ScheduleListView.as_view(), name='schedule-list'),
]

food_app/models.py
import uuid

from pathlib import Path

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail

from django_resized import ResizedImageField

# Create your models here.


def image_upload_handler(instance, filename):
    
    model_name = instance.__class__.__name__
    new_filename = uuid.uuid4().hex
    file_suffix = Path(filename).suffix
    
    return f'food_app/{model_name}/{new_filename}{file_suffix}'


class User(AbstractUser):

    class Meta:
            verbose_name = 'Użytkownik'
            verbose_name_plural = 'Użytkownicy'

    first_name = models.CharField(verbose_name='Imię', max_length=64)
    last_name = models.CharField(verbose_name='Nazwisko', max_length=64)
    password = models.CharField(verbose_name='Hasło', max_length=128)
    is_active = models.BooleanField(verbose_name='Aktywny', default=False)
    username = models.CharField(
        verbose_name='Nazwa użytkownika',
        max_length=64,
        unique=True,
        error_messages={'unique': 'Nazwa użytkownika już zarejestrowana w serwisie'},
        )
    email = models.EmailField(
        verbose_name='Email',
        max_length=128,
        unique=True,
        error_messages={'unique': 'Email już zarejestrowany w serwisie'},
        )
    avatar = ResizedImageField(
        size=[192, 256],
        crop=['middle', 'center'],
        force_format='PNG',
        upload_to=image_upload_handler,
        default='food_app/default_person.png',
        verbose_name='Awatar'
        )
    
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):

        return self.username
    
    def get_full_name(self):
        
        return f'{self.first_name} {self.last_name}'

    def email_user(self, subject, message, from_email='webmaster@localhost', *args, **kwargs):
        
        send_mail(subject, message, from_email, [self.email,], *args, **kwargs)


class UserUniqueToken(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class Ingredient(models.Model):

    class Meta:
        verbose_name = 'Składnik'
        verbose_name_plural = 'Składniki'
        ordering = ['name']

    name = models.CharField(
        verbose_name='Nazwa składnika',
        max_length=128,
        unique=True,
        error_messages={'unique': 'Składnik już zapisany w bazie'},
        )
    create_by = models.ForeignKey(
        'User',
        related_name='ingredients',
        verbose_name='Stworzył',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    
    class Meta:
        verbose_name = 'Przepis'
        verbose_name_plural = 'Przepisy'
        ordering = ['name']
    
    name = models.CharField(verbose_name='Nazwa przepisu', max_length=128)
    description = models.TextField(verbose_name='Opis przepisu', null=True, blank=True)
    preparing = models.TextField(verbose_name='Sposób przygotowania')
    create_date = models.DateTimeField(verbose_name='Data dodania', auto_now_add=True)
    preparation_time = models.DurationField(verbose_name='Czas przygotowania')
    calories = models.PositiveSmallIntegerField(verbose_name='Ilość kalorii / 100 gram', null=True, blank=True)
    create_by = models.ForeignKey(
        'User',
        related_name='recipes',
        verbose_name='Stworzył',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )
    ingredients = models.ManyToManyField(
        'Ingredient',
        related_name='recipes',
        verbose_name='Składniki',
        through='IngredientRecipe',
        )
    comments = models.ManyToManyField(
        'User',
        related_name='comments',
        verbose_name='Komentarze',
        through='CommentRecipe',
        )
    likes = models.ManyToManyField(
        'User',
        related_name='likes',
        verbose_name='Polubienia',
        )
    image = ResizedImageField(
        size=[342, 256],
        crop=['middle', 'center'],
        force_format='PNG',
        upload_to=image_upload_handler,
        default='food_app/default_recipe.png',
        verbose_name='Zdjęcie'
        )
    
    def __str__(self):
        return self.name
    

class IngredientRecipe(models.Model):

    class Meta:
        verbose_name = 'Składnik przepisu'
        verbose_name_plural = 'Składnik przepisu'
        unique_together = ['ingredient', 'recipe']
        ordering = ['ingredient', 'recipe']

    quantity = models.CharField(verbose_name='Ilość', max_length=64)
    ingredient = models.ForeignKey(
        'Ingredient',
        related_name='ingredient_recipes',
        verbose_name='Składnik',
        on_delete=models.RESTRICT
        )
    recipe = models.ForeignKey(
        'Recipe',
        related_name='recipe_ingredients',
        verbose_name='Przepis',
        on_delete=models.CASCADE
        )
    
    def unique_error_message(self, model_class, unique_check):

        if unique_check == ('ingredient', 'recipe'):
            return 'Składnik już dodany do przepisu'

        return super().unique_error_message(model_class, unique_check)


class CommentRecipe(models.Model):

    class Meta:
        verbose_name = 'Komentarz przepisu'
        verbose_name_plural = 'Komentarz przepisu'
        ordering = ['-date_added']

    comment = models.TextField(verbose_name='Komentarz')
    date_added = models.DateTimeField(verbose_name='Data wpisu', auto_now_add=True)
    recipe = models.ForeignKey(
        'Recipe',
        related_name='recipe_comments',
        verbose_name='Przepis',
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        'User',
        related_name='user_comments',
        verbose_name='Użytkownik',
        on_delete=models.CASCADE
        )


class Schedule(models.Model):
    
    class Meta:
        verbose_name = 'Plan'
        verbose_name_plural = 'Plany'
        ordering = ['name']
    
    name = models.CharField(verbose_name='Nazwa planu', max_length=128)
    description = models.TextField(verbose_name='Opis planu', null=True, blank=True)
    create_date = models.DateTimeField(verbose_name='Data dodania', auto_now_add=True)
    create_by = models.ForeignKey(
        'User',
        related_name='schedules',
        verbose_name='Stworzył',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )
    recipes = models.ManyToManyField(
        'Recipe',
        related_name='schedules',
        verbose_name='Przepisy',
        through='RecipeSchedule',
        )
    likes = models.ManyToManyField(
        'User',
        related_name='likes_schedule',
        verbose_name='Polubienia',
        )
    
    def __str__(self):
        return self.name
 

class RecipeSchedule(models.Model):
    
    class Meta:
        verbose_name = 'Przepis w planie'
        verbose_name_plural = 'Przepisy w planie'
        unique_together = ['schedule', 'day_number', 'meal_number']
        ordering = ['schedule', 'day_number', 'meal_number']

    DAY_CHOICES = (
        (1, 'Poniedziałek'),
        (2, 'Wtorek'),
        (3, 'Środa'),
        (4, 'Czwartek'),
        (5, 'Piątek'),
        (6, 'Sobota'),
        (7, 'Niedziela')
    )
    MEAL_CHOICES = (
        (1, 'Śniadanie'),
        (2, 'Drugie śniadanie'),
        (3, 'Obiad'),
        (4, 'Podwieczorek'),
        (5, 'Kolacja')
    )
    
    day_number = models.PositiveSmallIntegerField(verbose_name='Dzień tygodnia', choices=DAY_CHOICES)
    meal_number = models.PositiveSmallIntegerField(verbose_name='Posiłek', choices=MEAL_CHOICES)
    schedule = models.ForeignKey(
        'Schedule',
        related_name='schedule_recipes',
        verbose_name='Plan',
        on_delete=models.CASCADE
        )
    recipe = models.ForeignKey(
        'Recipe',
        related_name='recipe_schedules',
        verbose_name='Przepis',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
        )

    def unique_error_message(self, model_class, unique_check):

        if unique_check == ('schedule', 'day_number', 'meal_number'):
            return 'Posiłek już ujęty w tym dniu w planie'

        return super().unique_error_message(model_class, unique_check)

food_app/templates/food_app/recipe_delete.html
{% extends 'food_app/main.html' %}
{% block content_main %}
<div class="container-card-style">
    <form class="form-style" action="" method="POST">
        {% csrf_token %}
        <div class="row row-header-style">
            <div class="col d-flex">
                <h5 class="text-uppercase">Usuń przepis</h5>
            </div>
            <div class="col d-flex justify-content-end">
                <a href="{{ request.GET.next }}" class="btn button-style">Anuluj</a>
                <button type="submit" class="button-style">Potwierdź</button>
            </div>
        </div>
        <div class="row row-form-style">
            <div class="col-lg-4 col-md-3 col-sm-2"></div>
            <div class="col-lg-4 col-md-6 col-sm-8">
                <p class="text-center">
                    <strong>Potwierdź usunięcie przepisu - {{ recipe }}</strong>
                </p>
            </div>
            <div class="col-lg-4 col-md-3 col-sm-2"></div>
        </div>
    </form>
</div>
{% endblock %}

food_app/templates/food_app/recipe_form_step3.html
{% extends 'food_app/main.html' %}
{% block content_main %}
<div class="container-card-style">
    <form class="form-style" action="" method="POST">
        {% csrf_token %}
        {{ wizard.management_form }}
        <div class="row row-header-style">
            <div class="col-8 d-flex">
                <h5 class="text-uppercase">
                    {% if recipe %}
                        Edytuj przepis
                    {% else %}
                        Dodaj przepis
                    {% endif %}
                </h5>
            </div>
            <div class="col-4 d-flex justify-content-end">
                <a href="{{ request.GET.next }}" class="btn button-style">Anuluj</a>
                {% if wizard.steps.prev %}
                    <button type="submit" name="wizard_goto_step" value="{{ wizard.steps.prev }}" class="btn button-style">Wstecz</button>
                {% endif %}
                <button type="submit" class="button-style">Dalej</button>
            </div>
        </div>
        <div class="row row-card-style">
            <div class="col-12">
                <h5>Przygotowanie - krok {{ wizard.steps.step1 }} / {{ wizard.steps.count }}</h5>
            </div>
        </div>
        <div class="row row-form-style">
            <div class="col-2 label-style">{{ form.preparing.label }}</div>
            <div class="col-10">
                {{ form.preparing }}
                {{ form.preparing.errors }}
            </div>
        </div>
    </form>
</div>
{% endblock content_main %}

food_app/templates/food_app/schedule_detail.html
{% extends 'food_app/main.html' %}
{% block content_main %}
<div class="container-card-style">
    <div class="row row-header-style">
        <div class="col">
            <h5 class="text-uppercase">Plan Żywienia</h5>
            <ul class="list-none-style">
                <li>Nazwa: <b>{{ schedule }}</b></li>
                <li>Polubienia: <i class="fa fa-thumbs-up"></i> <b>{{ schedule.likes.count }}</b>
                    {% if request.user.is_authenticated %}
                        <form class="form-like-style" action="" method="POST">
                            {% csrf_token %}
                            {% if user_like %}
                                <button type="submit" name="button_schedule" value="like_down" title="Usuń głos">
                                    <i class="fa fa-thumbs-down"></i>
                                </button>
                            {% else %}
                                <button type="submit" name="button_schedule" value="like_up" title="Oddaj głos">
                                    <i class="fa fa-thumbs-up"></i>
                                </button>
                            {% endif %}
                        </form>
                    {% else %}
                        <i class="fa fa-thumbs-up"></i>
                    {% endif %}
                </li>
                <li>Dodano: <b>{{ schedule.create_date|date:'j E Y' }}</b></li>
                {% if schedule.create_by %}
                    <li>Stworzył: <a href="{% url 'user-schedules' pk=schedule.create_by.pk %}">{{ schedule.create_by }}</a></li>
                {% endif %}
            </ul>    
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col-12">
            <h5>Opis planu żywienia</h5>
            <p class="text-style">{{ schedule.description }}</p>
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col-12">
            <h5>Harmonogram żywienia</h5>
            {% for item in schedule.schedule_recipes.all %}
                {% if forloop.counter0|divisibleby:5 != 0 %}
                    <div class="row row-card-style">
                        <div class="col">
                            <b>{{ item.get_day_number_display }}</b>
                        </div>
                    </div>
                {% endif %}
                <div class="row row-card-style-2">
                    <div class="col-lg-2 col-md-3 col-sm-4">
                        {{ item.get_meal_number_display }}
                    </div>
                    <div class="col">
                        {% if item.recipe %}
                            <a href="{% url 'recipe-detail' pk=item.recipe.pk %}" title="Szczegóły">
                                {{ item.recipe }}
                            </a>
                        {% else %}
                            -----
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content_main %}

food_app/templates/food_app/user_ingredient.html
{% extends 'food_app/user_panel.html' %}
{% block content_user_panel %}
    <div class="row row-card-style" id="user-ingredient">
        <div class="col-lg-9 col-md-8 col-sm-7 d-flex">
            <h5>
                {% if search_count or search_count == 0 %}
                    Znaleziono {{ search_count }}
                {% else %}
                    Twoje Składniki
                {% endif %}
                {% if is_paginated %}
                    <span class="pagination-style">
                        {% if page_obj.number > 1 %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'-1' }}#user-ingredient">&laquo;</a>
                        {% endif %}
                        {% if page_obj.paginator.num_pages <= 1 %}
                            {{ pass }}
                        {% else %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    {{ i }}
                                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                    <a href="{{ path_pagination }}{{ i }}#user-ingredient">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if page_obj.paginator.num_pages > page_obj.number %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'1' }}#user-ingredient">&raquo;</a>
                        {% endif %}
                    </span>
                {% endif %}
            </h5>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 d-flex justify-content-end">
            <form action="{% url 'user-ingredient' %}#user-ingredient" method="GET" class="form-style search-form-style">
                {{ form.name }}
                <button type="submit" title="Szukaj"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col">
            <table class="table table-style">
                <tbody>
                    {% for ingredient in ingredient_list %}
                        <tr>
                            <td class="col-10">
                                <b>{{ ingredient.name }}</b>
                            </td>
                            <td class="col-1 text-center">
                                <a href="{% url 'ingredient-update' pk=ingredient.pk %}?next={{ request.get_full_path }}" title="Edytuj">
                                    <i class="far fa-edit"></i>
                                </a>    
                            </td>
                            <td class="col-1 text-center">
                                <a href="{% url 'ingredient-delete' pk=ingredient.pk %}?next={{ request.get_full_path }}" title="Usuń">
                                    <i class="far fa-minus-square danger-style"></i>
                                </a>    
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content_user_panel %}

food_app/templates/food_app/user_like_schedule.html
{% extends 'food_app/user_panel.html' %}
{% block content_user_panel %}
    <div class="row row-card-style" id="user-like-schedule">
        <div class="col-lg-9 col-md-8 col-sm-7 d-flex">
            <h5>
                {% if search_count or search_count == 0 %}
                    Znaleziono {{ search_count }}
                {% else %}
                    Twoje polubione plany żywienia
                {% endif %}
                {% if is_paginated %}
                    <span class="pagination-style">
                        {% if page_obj.number > 1 %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'-1' }}#user-like">&laquo;</a>
                        {% endif %}
                        {% if page_obj.paginator.num_pages <= 1 %}
                            {{ pass }}
                        {% else %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    {{ i }}
                                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                    <a href="{{ path_pagination }}{{ i }}#user-like">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if page_obj.paginator.num_pages > page_obj.number %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'1' }}#user-like">&raquo;</a>
                        {% endif %}
                    </span>
                {% endif %}
            </h5>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 d-flex justify-content-end">
            <form action="{% url 'user-like' %}#user-like" method="GET" class="form-style search-form-style">
                {{ form.name }}
                <button type="submit" title="Szukaj"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col">
            <table class="table table-style">
                <tbody>
                    {% for schedule in schedule_list %}
                        <tr>
                            <td class="col-10">
                                <ul>
                                    <li>
                                        <a href="{% url 'schedule-detail' pk=schedule.pk %}" title="Szczegóły">{{ schedule.name }}</a>
                                    </li>
                                    <li>Dodano: {{ schedule.create_date|date:'j E Y' }}</li>
                                </ul>
                            </td>
                            <td class="col-1 text-center">
                                <i class="fa fa-thumbs-up"></i> {{ schedule.likes.count }}
                            </td>
                            <td class="col-1 text-center">
                                <form class="form-like-style" action="" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" name="like" value="{{ schedule.pk }}" title="Usuń głos">
                                        <i class="fa fa-thumbs-down"></i>
                                    </button>
                                </form> 
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content_user_panel %}

food_app/templates/food_app/user_recipe.html
{% extends 'food_app/user_panel.html' %}
{% block content_user_panel %}
    <div class="row row-card-style" id="user-recipe">
        <div class="col-lg-9 col-md-8 col-sm-7 d-flex">
            <h5>
                {% if search_count or search_count == 0 %}
                    Znaleziono ({{ search_count }})
                {% else %}
                    Twoje Przepisy
                {% endif %}
                {% if is_paginated %}
                    <span class="pagination-style">
                        {% if page_obj.number > 1 %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'-1' }}#user-recipe">&laquo;</a>
                        {% endif %}
                        {% if page_obj.paginator.num_pages <= 1 %}
                            {{ pass }}
                        {% else %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    {{ i }}
                                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                    <a href="{{ path_pagination }}{{ i }}#user-recipe">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if page_obj.paginator.num_pages > page_obj.number %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'1' }}#user-recipe">&raquo;</a>
                        {% endif %}
                    </span>
                {% endif %}
            </h5>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 d-flex justify-content-end">
            <form action="{% url 'user-recipe' %}#user-recipe" method="GET" class="form-style search-form-style">
                {{ form.name }}
                <button type="submit" title="Szukaj"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col">
            <table class="table table-style">
                <tbody>
                    {% for recipe in recipe_list %}
                        <tr>
                            <td class="col-1"><img src="{{ recipe.image.url }}"></td>    
                            <td class="col-9">
                                <ul>
                                    <li>
                                        <a href="{% url 'recipe-detail' pk=recipe.pk %}" title="Szczegóły">{{ recipe.name }}</a>
                                    </li>
                                    <li>Ilość kalorii: {% if recipe.calories %} {{ recipe.calories }} {% else %} ----- {% endif %} kcal</li>
                                    <li>Oddane głosy: {{ recipe.votes.count }}</li>
                                </ul>
                            </td>
                            <td class="col-1 text-center">
                                <a href="{% url 'recipe-update' pk=recipe.pk %}?next={{ request.get_full_path }}" title="Edytuj">
                                    <i class="far fa-edit"></i>
                                </a>    
                            </td>
                            <td class="col-1 text-center danger-style">
                                <a href="{% url 'recipe-delete' pk=recipe.pk %}" title="Usuń">
                                    <i class="far fa-minus-square"></i>
                                </a>    
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content_user_panel %}

food_app/templates/food_app/user_recipes.html
{% extends 'food_app/user_menu.html' %}
{% block content_user_menu %}
    <div class="row row-card-style" id="user-recipes">
        <div class="col-lg-9 col-md-8 col-sm-7 d-flex">
            <h5>
                {% if search_count or search_count == 0 %}
                    Znaleziono ({{ search_count }})
                {% else %}
                    Przepisy
                {% endif %}
                {% if is_paginated %}
                    <span class="pagination-style">
                        {% if page_obj.number > 1 %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'-1' }}#user-recipes">&laquo;</a>
                        {% endif %}
                        {% if page_obj.paginator.num_pages <= 1 %}
                            {{ pass }}
                        {% else %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    {{ i }}
                                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                    <a href="{{ path_pagination }}{{ i }}#user-recipes">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if page_obj.paginator.num_pages > page_obj.number %}
                            <a href="{{ path_pagination }}{{ page_obj.number|add:'1' }}#user-recipes">&raquo;</a>
                        {% endif %}
                    </span>
                {% endif %}
            </h5>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 d-flex justify-content-end">
            <form action="{% url 'user-recipes' pk=user.pk %}#user-recipes" method="GET" class="form-style search-form-style">
                {{ form.name }}
                <button type="submit" title="Szukaj"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
    <div class="row row-card-style">
        <div class="col">
            <table class="table table-style">
                <tbody>
                    {% for recipe in recipe_list %}
                        <tr>
                            <td class="col-1"><img src="{{ recipe.image.url }}"></td>    
                            <td class="col-11">
                                <ul>
                                    <li>
                                        <a href="{% url 'recipe-detail' pk=recipe.pk %}" title="Szczegóły">{{ recipe.name }}</a>
                                    </li>
                                    <li>Ilość kalorii: {% if recipe.calories %} {{ recipe.calories }} {% else %} ----- {% endif %} kcal</li>
                                    <li>Oddane głosy: {{ recipe.votes.count }}</li>
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content_user_menu %}